language: c
script: "make test"
notifications:
  irc:
    channels:
      - "chat.freenode.net#selenium"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
